### ISSUE TITLE
care to try these again? and error.BAD_CAPTCHA.field-captcha

### ISSUE THREAD

**Issue by madhabkirank** [Zetaphor/reddit-api-client#27]
I am usable to submit url , iam getting these two error ,
care to try these again?
error.BAD_CAPTCHA.field-captcha

**Comment by Zetaphor** [comment]
Typically you will get captcha requests if your account is still new and/or unverified. If you do the following, you should lose the captcha:

* Make more posts/comments
* Verify the email address on the account
* Wait more time until you lose the "New User" badge
